{% set name = "simwrapper" %}
{% set version = "1.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simwrapper-{{ version }}.tar.gz
  sha256: 3b6bc05214e48ac1c70128781bc1e7808cf7b53648c0ad4cf648aad2ec13deb1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - simwrapper = simwrapper.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - simwrapper
  commands:
    - pip check
    - simwrapper --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simwrapper/simwrapper-python-tools
  summary: Python support library for SimWrapper data visualization tool
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - billyc
